#!/usr/bin/env bash

set -a
BRIGHTNESS_FILE=`find /sys/devices/pci0000:00/ | grep intel_backlight/brightness`

old=$(< $BRIGHTNESS_FILE)
new=$(($old-200))
if [[ "$new" -gt 99 ]] && [[ "$new" -lt 801 ]]
    then echo $new > $BRIGHTNESS_FILE
fi
